# -*- mode: ruby -*-
# vi: set ft=ruby :

source 'https://rubygems.org'

group :devops do
  gem 'berkshelf'       , '1.4.3'
  gem 'chef'            , '11.4.4'
  gem 'foodcritic'      , '2.1.0'
  gem 'kitchen-vagrant' , '0.9.0'
  gem 'test-kitchen'    , github: 'opscode/test-kitchen'
  gem 'vagrant'         , github: 'mitchellh/vagrant', ref: 'v1.2.2'
  gem 'veewee'          , github: 'jedi4ever/veewee'
end
